name: Run Tests and Send Report to Qase

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test > result.json

      - name: Send test results to Qase
        run: |
          curl -X POST https://api.qase.io/v1/result/LP/run/{1} \
          -H "Content-Type: application/json" \
          -H "Token: ${{ secrets.QASE_API_TOKEN }}" \
          -d @result.json
